"""empty message

Revision ID: 0102be8998ba
Revises: 
Create Date: 2018-05-22 11:24:47.529400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0102be8998ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfacetests', sa.Column('interface_testnum', sa.String(length=252), nullable=True))
    op.create_foreign_key(None, 'interfacetests', 'interfacetests', ['pid'], ['id'])
    op.create_unique_constraint(None, 'projects', ['project_name'])
    op.create_foreign_key(None, 'tasks', 'projects', ['prject'], ['id'])
    op.create_foreign_key(None, 'tasks', 'ceshihuanjing', ['testevent'], ['id'])
    op.drop_column('tasks', 'taskdesc')
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_column('interfacetests', 'interface_testnum')
    # ### end Alembic commands ###
