"""empty message

Revision ID: 130ecd31a00a
Revises: 06bfb5c8f270
Create Date: 2019-04-23 13:12:55.155345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130ecd31a00a'
down_revision = '06bfb5c8f270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('sqlfiled', sa.String(length=252), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_column('actions', 'sqlfiled')
    # ### end Alembic commands ###
