"""empty message

Revision ID: 1f540eb8fd5e
Revises: 130ecd31a00a
Create Date: 2019-04-24 13:50:37.883900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f540eb8fd5e'
down_revision = '130ecd31a00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sceness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=252), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parame', sa.String(length=252), nullable=True),
    sa.Column('assertparame', sa.String(length=252), nullable=True),
    sa.Column('center', sa.String(length=128), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('testgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=252), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_table('testgroup')
    op.drop_table('sceness')
    # ### end Alembic commands ###
