"""empty message

Revision ID: 2488b2a0a217
Revises: a06da5b5dc5c
Create Date: 2019-04-22 16:45:30.004076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2488b2a0a217'
down_revision = 'a06da5b5dc5c'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('err_num', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('freetime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_free', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'is_free')
    op.drop_column('users', 'freetime')
    op.drop_column('users', 'err_num')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
