"""empty message
Revision ID: 2e7592889dea
Revises: 
Create Date: 2018-06-26 09:43:56.068165
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '2e7592889dea'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfacetests', sa.Column('bian_num', sa.String(length=252), nullable=True))
    op.create_foreign_key(None, 'interfacetests', 'interfacetests', ['pid'], ['id'])
    op.create_unique_constraint(None, 'projects', ['project_name'])
    op.create_foreign_key(None, 'tasks', 'ceshihuanjing', ['testevent'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['prject'], ['id'])
    op.drop_column('tasks', 'taskdesc')
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_column('interfacetests', 'bian_num')
    # ### end Alembic commands ###