"""empty message

Revision ID: 584609cbbba3
Revises: 
Create Date: 2018-03-14 15:09:41.332705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584609cbbba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mockserver', sa.Column('project', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mockserver', 'projects', ['project'], ['id'])
    op.create_unique_constraint(None, 'projects', ['project_name'])




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'mockserver', type_='foreignkey')
    op.drop_column('mockserver', 'project')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
