"""empty message

Revision ID: 661333708602
Revises: 
Create Date: 2018-04-13 13:08:56.030970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661333708602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_foreign_key(None, 'parames', 'users', ['user_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'parames', type_='foreignkey')
    op.drop_column('parames', 'user_id')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
