"""empty message

Revision ID: 66941f7b47d7
Revises: 0cf6cb1ed5ac
Create Date: 2017-08-14 21:03:32.100239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66941f7b47d7'
down_revision = '0cf6cb1ed5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('work_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'work_id')
    op.drop_column('users', 'role_id')
    op.drop_table('works')
    op.drop_table('roles')
    # ### end Alembic commands ###
