"""inition migrate

Revision ID: 6cbff83b0926
Revises: 
Create Date: 2017-11-15 14:55:55.187772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbff83b0926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailReports', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('interfaces', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('interfacetests', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('tstresults', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.drop_column('tstresults', 'status')
    op.drop_column('interfacetests', 'status')
    op.drop_column('interfaces', 'status')
    op.drop_column('emailReports', 'status')
    # ### end Alembic commands ###
