"""empty message

Revision ID: 85d0a8a66a8e
Revises: 
Create Date: 2018-09-18 09:22:10.776262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d0a8a66a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('userparmeters', sa.Column('status', sa.Boolean(), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('userparmeters', 'status')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
