"""empty message

Revision ID: 8d199e28cc5c
Revises: ebc4e65da033
Create Date: 2018-03-07 15:06:09.500249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d199e28cc5c'
down_revision = 'ebc4e65da033'
branch_labels = None
depends_on = None


def upgrade():
    op.create_foreign_key(None, 'tasks', 'projects', ['prject'], ['id'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
