"""empty message

Revision ID: 9a37e13f3cd3
Revises: 
Create Date: 2021-09-25 18:30:22.549661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a37e13f3cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###

    op.add_column('testcaseresults', sa.Column('by', sa.Boolean(), nullable=True))
    op.add_column('testcaseresults', sa.Column('spend', sa.String(length=52), nullable=True))
    op.add_column('testjmx', sa.Column('name', sa.String(length=252), nullable=True))
    op.add_column('testservers', sa.Column('is_run', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.drop_column('testservers', 'is_run')
    op.drop_column('testjmx', 'name')
    op.drop_column('testcaseresults', 'spend')
    op.drop_column('testcaseresults', 'by')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
