"""empty message

Revision ID: 9d1475d26465
Revises: 
Create Date: 2018-03-09 14:47:50.240457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1475d26465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ceshihuanjing', sa.Column('dbhost', sa.String(length=255), nullable=True))
    op.add_column('ceshihuanjing', sa.Column('dbport', sa.String(length=255), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_column('ceshihuanjing', 'dbport')
    op.drop_column('ceshihuanjing', 'dbhost')
    # ### end Alembic commands ###
