"""empty message

Revision ID: a06da5b5dc5c
Revises: 6c1c070f3663
Create Date: 2019-04-22 14:25:38.872131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06da5b5dc5c'
down_revision = '6c1c070f3663'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('jobnum', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'jobnum')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
