"""empty message

Revision ID: a7f37bdff9fb
Revises: 
Create Date: 2018-03-08 13:23:43.764832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f37bdff9fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfacetests', sa.Column('chaxunshujuku', sa.String(length=252), nullable=True))
    op.add_column('interfacetests', sa.Column('databaseziduan', sa.String(length=252), nullable=True))
    op.add_column('interfacetests', sa.Column('is_database', sa.Boolean(), nullable=True))
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_column('interfacetests', 'is_database')
    op.drop_column('interfacetests', 'databaseziduan')
    op.drop_column('interfacetests', 'chaxunshujuku')
    # ### end Alembic commands ###
