"""empty message

Revision ID: c1d14471dca7
Revises: 
Create Date: 2017-08-16 16:19:27.119646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d14471dca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstresults', sa.Column('projects_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.drop_column('tstresults', 'projects_name')
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('tstresults', sa.Column('projects_name', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.drop_column('tstresults', 'projects_id')
    # ### end Alembic commands ###
