"""empty message

Revision ID: c207f85b2700
Revises: 
Create Date: 2017-08-15 14:11:16.643410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c207f85b2700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailReports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_re_user_id', sa.Integer(), nullable=True),
    sa.Column('send_email', sa.String(length=64), nullable=True),
    sa.Column('send_email_password', sa.String(length=64), nullable=True),
    sa.Column('to_email', sa.String(), nullable=True),
    sa.Column('default_set', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_re_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('emailReports')
    # ### end Alembic commands ###
