"""empty message

Revision ID: c8cdca91afc0
Revises: 1f540eb8fd5e
Create Date: 2020-05-07 20:02:36.173008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cdca91afc0'
down_revision = '1f540eb8fd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testgroup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=252), nullable=True),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('adduser', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.Date(), nullable=True),
    sa.Column('updateuser', sa.Integer(), nullable=True),
    sa.Column('updatetime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'interfacetests', 'interfacetests', ['pid'], ['id'])
    op.create_unique_constraint(None, 'projects', ['project_name'])
    op.create_foreign_key(None, 'tasks', 'ceshihuanjing', ['testevent'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['prject'], ['id'])
    op.drop_column('tasks', 'taskdesc')
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_table('testgroup')
    # ### end Alembic commands ###
