"""empty message

Revision ID: e1b0239c86a4
Revises: 0e7583df376e
Create Date: 2018-08-24 15:02:52.754150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b0239c86a4'
down_revision = '0e7583df376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.add_column('projects', sa.Column('desc', sa.String(length=252), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'desc')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'project')
    op.drop_column('models', 'common')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
