"""empty message

Revision ID: e7e04f5c29d4
Revises: 
Create Date: 2017-11-15 16:51:18.415758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e04f5c29d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfacetests', sa.Column('Interface_is_tiaoshi', sa.Boolean(), nullable=True))
    op.add_column('interfacetests', sa.Column('Interface_tiaoshi_shifou', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tstresults', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'users', 'works', ['work_id'], ['id'])
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.drop_column('interfacetests', 'Interface_tiaoshi_shifou')
    op.drop_column('interfacetests', 'Interface_is_tiaoshi')
    # ### end Alembic commands ###
