"""empty message

Revision ID: e8068c4943a4
Revises: 
Create Date: 2019-02-20 13:50:19.921158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8068c4943a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caseactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('actiontype', sa.Integer(), nullable=True),
    sa.Column('filed', sa.String(length=252), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['case'], ['interfacetests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casegenerals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case', sa.Integer(), nullable=True),
    sa.Column('general', sa.Integer(), nullable=True),
    sa.Column('filed', sa.String(length=252), nullable=True),
    sa.ForeignKeyConstraint(['case'], ['interfacetests.id'], ),
    sa.ForeignKeyConstraint(['general'], ['generalconfigurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    op.drop_table('casegenerals')
    op.drop_table('caseactions')
    # ### end Alembic commands ###
