"""empty message

Revision ID: ebc4e65da033
Revises: 
Create Date: 2018-03-01 16:20:56.016762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc4e65da033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('tstresults', sa.Column('Exception_num', sa.Integer(), nullable=True))
    op.add_column('tstresults', sa.Column('can_num', sa.Integer(), nullable=True))
    op.add_column('tstresults', sa.Column('wei_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tstresults', type_='foreignkey')
    op.drop_column('tstresults', 'wei_num')
    op.drop_column('tstresults', 'can_num')
    op.drop_column('tstresults', 'Exception_num')
    op.add_column('tasks', sa.Column('taskdesc', sa.TEXT(length=252), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'interfacetests', type_='foreignkey')
    # ### end Alembic commands ###
